### ISSUE TITLE
Using the test framework with Account Linking

### ISSUE THREAD

**Issue by fvisticot** [yoichiro/dialogflow-query-checker#16]
I try to use this test framework with Google Account Linking feature.
I get this error:

[Query: ou sont mes tibes ()]
  Failure: status is 206, not 200. (partial_content: Webhook call failed. Error: Request timeout.)
    Expected: 200
    Actual: 206
  Failure: endConversation is not same as expected value.

is the Account Linking feature supported with this test framework ?

**Comment by yoichiro** [comment]
> is the Account Linking feature supported with this test framework ?

@fvisticot Currently, no. But, I'd like to support the feature. Could you give me a few days to think a spec to support it?

**Comment by fvisticot** [comment]
If you need a Beta tester I will be ready for that !

Fred

**Comment by yoichiro** [comment]
@fvisticot In the latest version of this tool, a debug mode has been supporting with the `-d` option. Could you send me an output log with the debug mode? I will be able to know more details about a behavior of the account linking.

**Comment by yoichiro** [comment]
@fvisticot Hmm... Is the issue you're having really about the account linking feature?

> Failure: status is 206, not 200. (partial_content: Webhook call failed. Error: Request timeout.)

At least, it seems that the error message mans that the Dialogflow could not call your fulfillment's endpoint URL. Currently, all fulfillments need to respond within 5 sec. I guess that your fulfillment could not respond within the time at the time. In addition, the error does not relate the account linking feature, I guess...

Why did you think that the error message relates to the account linking feature?

**Comment by fvisticot** [comment]
Hello,

The bot is working perfectly in production (Google validated)
I really think it is due to account linking. Somewhere in the test, i could be able to set my gmail account or equivalent

The Yaml:

clientAccessToken: < I can give it to you by private mail >
defaultLanguage: fr
defaultLocale: fr-FR
tests:
  -
    condition:
      contexts:
        - 
      language: fr
      locale: fr-FR
      query: ou sont mes clefs
    expect:
      action: locate
      intentName: locate
      parameters:
        object-type: tibe
      speeches:
        - 
      endConversation: false


The traces:


MacBook-Pro-de-frederic:darwin_386 $ ./dialogflow-query-checker run test.yaml -d
dialogflow-query-checker version 1.11.0
The configuration file loaded: test.yaml
The debug mode is on
The count of retrying: 0
Running query tests for Dialogflow.
[Start] Query: ou sont mes clefs ()
<Request body> {
  "contexts": [
    ""
  ],
  "lang": "fr",
  "originalRequest": {
    "source": "google",
    "data": {
      "user": {
        "locale": "fr-FR"
      }
    }
  },
  "query": "ou sont mes clefs",
  "event": {},
  "sessionId": "54004e50-d0ee-44e0-b6e0-660e5b7a3ec8"
}
<Response Status> 200 OK
<Response body> {
  "id": "4c7101a8-9805-4db1-996c-0c088bf50b1a",
  "timestamp": "2018-03-02T06:51:51.162Z",
  "lang": "fr",
  "result": {
    "source": "agent",
    "resolvedQuery": "ou sont mes clefs",
    "action": "locate",
    "actionIncomplete": true,
    "parameters": {
      "object-name": "",
      "object-type": ""
    },
    "contexts": [
      {
        "name": "locate_dialog_params_object-name",
        "parameters": {
          "object-name.original": "",
          "object-name": "",
          "object-type": "",
          "object-type.original": ""
        },
        "lifespan": 1
      },
      {
        "name": "cb6c068e-2788-4189-afaa-85173e45f8e1_id_dialog_context",
        "parameters": {
          "object-name.original": "",
          "object-name": "",
          "object-type": "",
          "object-type.original": ""
        },
        "lifespan": 2
      },
      {
        "name": "locate_dialog_context",
        "parameters": {
          "object-name.original": "",
          "object-name": "",
          "object-type": "",
          "object-type.original": ""
        },
        "lifespan": 2
      },
      {
        "name": "",
        "parameters": {
          "object-name.original": "",
          "object-name": "",
          "object-type": "",
          "object-type.original": ""
        },
        "lifespan": 5
      }
    ],
    "metadata": {
      "intentId": "cb6c068e-2788-4189-afaa-85173e45f8e1",
      "webhookUsed": "true",
      "webhookForSlotFillingUsed": "true",
      "webhookResponseTime": 10000,
      "intentName": "locate"
    },
    "fulfillment": {
      "speech": "Quel objet voulez vous localiser ?",
      "messages": [
        {
          "type": 0,
          "speech": "Quel objet voulez vous localiser ?"
        }
      ]
    },
    "score": 0.6700000166893005
  },
  "status": {
    "code": 206,
    "errorType": "partial_content",
    "errorDetails": "Webhook call failed. Error: Request timeout.",
    "webhookTimedOut": true
  },
  "sessionId": "54004e50-d0ee-44e0-b6e0-660e5b7a3ec8"
}
F..F.F
[End] Query: ou sont mes clefs ()

[Query: ou sont mes clefs ()]
  Failure: status is 206, not 200. (partial_content: Webhook call failed. Error: Request timeout.)
    Expected: 200
    Actual: 206
  Failure: object-type is not same as expected value.
    Expected: tibe
    Actual: 
  Failure: endConversation is not same as expected value.
    Expected: false
    Actual: true
Finished in 10.978952 seconds.
1 test failed.

**Comment by yoichiro** [comment]
@fvisticot Thank you for sending the information. I will check them soon. Just a moment.

**Comment by fvisticot** [comment]
Hello,
I think that the timeout occurs because the account linking is not established.
If I test with the simulator I get an answer to provide account linking information.


Regards,

Fred

**Comment by yoichiro** [comment]
@fvisticot Ok, I see. Well, could you send me the log of the "Request" tab on Actions Simulator when you invoke your app after the account linking was established? I guess that I may know your situation more details by checking the log.

**Comment by fvisticot** [comment]
Yep: the request:

{
  "user": {
    "userId": "ABwppHF3IIUlbUcuhVS6Vt0csX0D6h1rtRyXb_Fs1FoO2T0RVz3r0tZSsUrupE_WYWO2sLaTwf6fFw",
    "accessToken": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJvcmdhbml6YXRpb25JZCI6IkY5RUIzOUNDLTA4OTktNDFBMC05QTU1LTJGOTgyMEYwREU0NCIsImF1ZCI6WyJkZXZpY2VzIl0sInVzZXJfbmFtZSI6ImZ2aXN0aWNvdCt0aWJlQGdtYWlsLmNvbSIsInNjb3BlIjpbInJpbmdfZGV2aWNlcyIsInJlYWRfZGV2aWNlcyJdLCJsYW5ndWFnZSI6ImZyLUZSIiwidXNlcklkIjoiQjYyREUxMzQtOEM2NC00ODg4LThBRDUtMjlDNzAwRDhERUQwIiwiYXV0aG9yaXRpZXMiOlsiUk9MRV9VU0VSIl0sImp0aSI6IjBiZGMxNjcwLTI5YTAtNDNkNy05YjdmLTJkNTE3NmM5N2Q5NCIsImNsaWVudF9pZCI6Imdvb2dsZS1hY3Rpb24ifQ.kw7QmG7OS6bQIuIOdTVmwzo5OR5Z_3-J6wifv0F7B_DyYcfSCgC6cBL-_Zf_nMWH-vnBgpiw_a0boBk_E6acVUl629Kz0_DXpk0ivnIStMB58SiUnzYyUen9PQQ7DEdda83e03lad8AD9H8QkaNO5_peAIu2oZkIzYtWjh0cx0jjLclW8x5wn3lctUtEV_UIPiErvH9yIfwjkHLcRV64FGERu3gejwGxu5lrPMk8rCJHvV0dEmsqNRjAcqsW4Z5BOHBObjo7ZZBzfxEZ-t5XKXOYtCX4YSLjhfW8nbcluB_q7IE2TDu21xxM_PZnmmI_cmn8Kgq8geI5qPY-Ovtjdw",
    "locale": "en-US",
    "lastSeen": "2018-03-02T13:06:53Z",
    "userStorage": "{\"data\":{}}"
  },
  "conversation": {
    "conversationId": "1520025437791",
    "type": "NEW"
  },
  "inputs": [
    {
      "intent": "actions.intent.MAIN",
      "rawInputs": [
        {
          "inputType": "VOICE",
          "query": "Talk to Ticatag"
        }
      ]
    }
  ],
  "surface": {
    "capabilities": [
      {
        "name": "actions.capability.MEDIA_RESPONSE_AUDIO"
      },
      {
        "name": "actions.capability.WEB_BROWSER"
      },
      {
        "name": "actions.capability.AUDIO_OUTPUT"
      },
      {
        "name": "actions.capability.SCREEN_OUTPUT"
      }
    ]
  },
  "isInSandbox": true,
  "availableSurfaces": [
    {
      "capabilities": [
        {
          "name": "actions.capability.AUDIO_OUTPUT"
        },
        {
          "name": "actions.capability.SCREEN_OUTPUT"
        }
      ]
    }
  ]
}


Response:
{
  "conversationToken": "[\"_actions_on_google_\",\"devices\",\"devices_learned\"]",
  "expectUserResponse": true,
  "expectedInputs": [
    {
      "inputPrompt": {
        "richInitialPrompt": {
          "items": [
            {
              "simpleResponse": {
                "textToSpeech": "Welcome to Ticatag"
              }
            },
            {
              "simpleResponse": {
                "textToSpeech": "What do you want ?"
              }
            }
          ],
          "suggestions": [
            {
              "title": "Locate my tibe"
            },
            {
              "title": "Ring my tibe"
            },
            {
              "title": "Get support"
            }
          ]
        }
      },
      "possibleIntents": [
        {
          "intent": "assistant.intent.action.TEXT"
        }
      ],
      "speechBiasingHints": [
        "$object-name",
        "$object-type"
      ]
    }
  ],
  "responseMetadata": {
    "status": {},
    "queryMatchInfo": {
      "queryMatched": true,
      "intent": "15f85457-1d18-4cd8-b992-066e1491bf99"
    }
  }
}


Debug
{
  "audioResponse": "//NExAARWQ...",
  "conversationToken": "CiZDIzVhOT...",
  "debugInfo": {
    "agentToAssistantDebug": {
      "agentToAssistantJson": "{\"conversationToken\":\"[\\\"_actions_on_google_\\\",\\\"devices\\\",\\\"devices_learned\\\"]\",\"expectUserResponse\":true,\"expectedInputs\":[{\"inputPrompt\":{\"richInitialPrompt\":{\"items\":[{\"simpleResponse\":{\"textToSpeech\":\"Welcome to Ticatag\"}},{\"simpleResponse\":{\"textToSpeech\":\"What do you want ?\"}}],\"suggestions\":[{\"title\":\"Locate my tibe\"},{\"title\":\"Ring my tibe\"},{\"title\":\"Get support\"}]}},\"possibleIntents\":[{\"intent\":\"assistant.intent.action.TEXT\"}],\"speechBiasingHints\":[\"$object-name\",\"$object-type\"]}],\"responseMetadata\":{\"status\":{},\"queryMatchInfo\":{\"queryMatched\":true,\"intent\":\"15f85457-1d18-4cd8-b992-066e1491bf99\"}}}"
    },
    "assistantToAgentDebug": {
      "assistantToAgentJson": "{\"user\":{\"userId\":\"ABwppHF3IIUlbUcuhVS6Vt0csX0D6h1rtRyXb_Fs1FoO2T0RVz3r0tZSsUrupE_WYWO2sLaTwf6fFw\",\"accessToken\":\"eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJvcmdhbml6YXRpb25JZCI6IkY5RUIzOUNDLTA4OTktNDFBMC05QTU1LTJGOTgyMEYwREU0NCIsImF1ZCI6WyJkZXZpY2VzIl0sInVzZXJfbmFtZSI6ImZ2aXN0aWNvdCt0aWJlQGdtYWlsLmNvbSIsInNjb3BlIjpbInJpbmdfZGV2aWNlcyIsInJlYWRfZGV2aWNlcyJdLCJsYW5ndWFnZSI6ImZyLUZSIiwidXNlcklkIjoiQjYyREUxMzQtOEM2NC00ODg4LThBRDUtMjlDNzAwRDhERUQwIiwiYXV0aG9yaXRpZXMiOlsiUk9MRV9VU0VSIl0sImp0aSI6IjBiZGMxNjcwLTI5YTAtNDNkNy05YjdmLTJkNTE3NmM5N2Q5NCIsImNsaWVudF9pZCI6Imdvb2dsZS1hY3Rpb24ifQ.kw7QmG7OS6bQIuIOdTVmwzo5OR5Z_3-J6wifv0F7B_DyYcfSCgC6cBL-_Zf_nMWH-vnBgpiw_a0boBk_E6acVUl629Kz0_DXpk0ivnIStMB58SiUnzYyUen9PQQ7DEdda83e03lad8AD9H8QkaNO5_peAIu2oZkIzYtWjh0cx0jjLclW8x5wn3lctUtEV_UIPiErvH9yIfwjkHLcRV64FGERu3gejwGxu5lrPMk8rCJHvV0dEmsqNRjAcqsW4Z5BOHBObjo7ZZBzfxEZ-t5XKXOYtCX4YSLjhfW8nbcluB_q7IE2TDu21xxM_PZnmmI_cmn8Kgq8geI5qPY-Ovtjdw\",\"locale\":\"en-US\",\"lastSeen\":\"2018-03-02T13:06:53Z\",\"userStorage\":\"{\\\"data\\\":{}}\"},\"conversation\":{\"conversationId\":\"1520025437791\",\"type\":\"NEW\"},\"inputs\":[{\"intent\":\"actions.intent.MAIN\",\"rawInputs\":[{\"inputType\":\"VOICE\",\"query\":\"Talk to Ticatag\"}]}],\"surface\":{\"capabilities\":[{\"name\":\"actions.capability.MEDIA_RESPONSE_AUDIO\"},{\"name\":\"actions.capability.WEB_BROWSER\"},{\"name\":\"actions.capability.AUDIO_OUTPUT\"},{\"name\":\"actions.capability.SCREEN_OUTPUT\"}]},\"isInSandbox\":true,\"availableSurfaces\":[{\"capabilities\":[{\"name\":\"actions.capability.AUDIO_OUTPUT\"},{\"name\":\"actions.capability.SCREEN_OUTPUT\"}]}]}",
      "curlCommand": "curl -v 'https://api.api.ai/api/integrations/google?token=1a22c3f7fd24449480f34f409b2320d0' -H 'Content-Type: application/json;charset=UTF-8' -H 'Google-Actions-API-Version: 2' -H 'Authorization: eyJhbGciOiJSUzI1NiIsImtpZCI6IjgzOWI5MjRiYjY1OWYwNzM1OGZkZjgyODhjZTU5ZjE4OWM0MDI4ZjQifQ.eyJhdWQiOiJ0aWJlLTM4MDQwIiwiYXpwIjoiNjE0OTIwMDc5MjExLTI4OGNlZXZzdWlhcG1mNjJ1OHNiczJwazRhdDRkaTFvLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwiZXhwIjoxNTIwMDI1NTU4LCJpc3MiOiJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20iLCJqdGkiOiI5MzA3Yjc2OTAzM2FkMjZhMTBiMzc1MzljOWRhNWZmNWE4ZTMwYWJiIiwiaWF0IjoxNTIwMDI1NDM4LCJuYmYiOjE1MjAwMjUxMzh9.B8tz_afIbjTDr_i-cWGwjXlowcilVTNbl8LJgiZ_ZVf_PEVk68rdQpQZozxWPHPOfYOdqMij2VDJHHmSxuxJoG1opDUWL1VSH3-bIbkVZhDLzC6gd8hYMzCtEwwmQYtqTl1tbb7U2-Zq3RnO3gaE2pSMZP3GgCY4K-El2r2GKbhMPHBuFKJkMIyGO-TpX3uvwwP0e2mcHNHV4Yrr1XvnHPQzHBpeHf-bzCEO-gXbRjV0yXsDtC-8FVW-32yJtOb4EbDpF-6OAgHGT2l9oXsJirvC4fzMUe9-j3M01iaaC-57ej2y3BDXMCebmwcAEGOLP6CzeV5eqVzC9IfvYM97jQ'  -A 'Mozilla/5.0 (compatible; Google-Cloud-Functions/2.1; +http://www.google.com/bot.html)' -X POST -d '{\"user\":{\"userId\":\"ABwppHF3IIUlbUcuhVS6Vt0csX0D6h1rtRyXb_Fs1FoO2T0RVz3r0tZSsUrupE_WYWO2sLaTwf6fFw\",\"accessToken\":\"eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJvcmdhbml6YXRpb25JZCI6IkY5RUIzOUNDLTA4OTktNDFBMC05QTU1LTJGOTgyMEYwREU0NCIsImF1ZCI6WyJkZXZpY2VzIl0sInVzZXJfbmFtZSI6ImZ2aXN0aWNvdCt0aWJlQGdtYWlsLmNvbSIsInNjb3BlIjpbInJpbmdfZGV2aWNlcyIsInJlYWRfZGV2aWNlcyJdLCJsYW5ndWFnZSI6ImZyLUZSIiwidXNlcklkIjoiQjYyREUxMzQtOEM2NC00ODg4LThBRDUtMjlDNzAwRDhERUQwIiwiYXV0aG9yaXRpZXMiOlsiUk9MRV9VU0VSIl0sImp0aSI6IjBiZGMxNjcwLTI5YTAtNDNkNy05YjdmLTJkNTE3NmM5N2Q5NCIsImNsaWVudF9pZCI6Imdvb2dsZS1hY3Rpb24ifQ.kw7QmG7OS6bQIuIOdTVmwzo5OR5Z_3-J6wifv0F7B_DyYcfSCgC6cBL-_Zf_nMWH-vnBgpiw_a0boBk_E6acVUl629Kz0_DXpk0ivnIStMB58SiUnzYyUen9PQQ7DEdda83e03lad8AD9H8QkaNO5_peAIu2oZkIzYtWjh0cx0jjLclW8x5wn3lctUtEV_UIPiErvH9yIfwjkHLcRV64FGERu3gejwGxu5lrPMk8rCJHvV0dEmsqNRjAcqsW4Z5BOHBObjo7ZZBzfxEZ-t5XKXOYtCX4YSLjhfW8nbcluB_q7IE2TDu21xxM_PZnmmI_cmn8Kgq8geI5qPY-Ovtjdw\",\"locale\":\"en-US\",\"lastSeen\":\"2018-03-02T13:06:53Z\",\"userStorage\":\"{\\\"data\\\":{}}\"},\"conversation\":{\"conversationId\":\"1520025437791\",\"type\":\"NEW\"},\"inputs\":[{\"intent\":\"actions.intent.MAIN\",\"rawInputs\":[{\"inputType\":\"VOICE\",\"query\":\"Talk to Ticatag\"}]}],\"surface\":{\"capabilities\":[{\"name\":\"actions.capability.MEDIA_RESPONSE_AUDIO\"},{\"name\":\"actions.capability.WEB_BROWSER\"},{\"name\":\"actions.capability.AUDIO_OUTPUT\"},{\"name\":\"actions.capability.SCREEN_OUTPUT\"}]},\"isInSandbox\":true,\"availableSurfaces\":[{\"capabilities\":[{\"name\":\"actions.capability.AUDIO_OUTPUT\"},{\"name\":\"actions.capability.SCREEN_OUTPUT\"}]}]}'"
    }
  },
  "expectUserResponse": true,
  "response": "Welcome to Ticatag\nWhat do you want ?",
  "visualResponse": {
    "agentLogoUrl": "http://lh3.googleusercontent.com/JsYU4qhYdJc9feHv2lW72fWeXtO9zIPIGLlLs9lExOyi-uVURGGSu-zUSicwvgUxIDF5hPGCqEvP",
    "suggestions": [
      {
        "title": "Locate my tibe"
      },
      {
        "title": "Ring my tibe"
      },
      {
        "title": "Get support"
      }
    ],
    "visualElements": [
      {
        "displayText": {
          "content": "Welcome to Ticatag"
        }
      },
      {
        "displayText": {
          "content": "What do you want ?"
        }
      }
    ]
  }
}

**Comment by yoichiro** [comment]
@fvisticot Thank you for sending your log. I omitted it because it has sensitive information. Sorry.

**Comment by yoichiro** [comment]
Thank you for all information you gave me! I understand your situation, and I thought a specification to support the Account Linking feature.

Basically, an access token should be sent from this dialogflow-query-checker to your Dialogflow project for each request. That is, I need to define a place where you specify your access token for testing your app. Currently, I'm thinking the follow specification:

```yaml
...
defaultAccessToken: <DEFAULT_ACCESS_TOKEN>
...
tests:
  -
    condition:
      ...
      accessToken: <THE_ACCESS_TOKEN_FOR_THIS_REQUEST>
    expect:
      ...
...
```

@fvisticot Does the above sound good for you?

**Comment by yoichiro** [comment]
I guess that... dialogflow-query-checker users need to issue  some access tokens for each test in advance. Basically, an auth and authz flow consists of some screens for a sign-in and an approval. However, this test tool can't display any screens because of auto-testing...

**Comment by yoichiro** [comment]
In addition, I think that users should be able to specify the access token using a environment variable.

**Comment by yoichiro** [comment]
Pull Request: #26

**Comment by yoichiro** [comment]
@fvisticot I have just released a new version [1.13.0](https://github.com/yoichiro/dialogflow-query-checker/releases/tag/1.13.0) which supports Account Linking. You can specify an access token issued by your service. Could you use and test this latest version?

**Comment by fvisticot** [comment]
The new release 1.13 works with account linking !!

Tx

Fred

**Comment by yoichiro** [comment]
@fvisticot Ok, I close this issue. Thank you for the reporting.
